<?php

declare(strict_types=1);

namespace App\Tests\Functional;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * The addresses a Stimulus controller receives as a *template*, with a `__PLACEHOLDER__` where an id
 * will go.
 *
 * They are generated by path() at render time, so a `\d+` requirement on the placeholder's parameter
 * makes the generator throw - and the exception surfaces while rendering the page, as a 500 on a
 * screen that has nothing to do with the route being named. That is exactly how
 * /tools/videos/{id}/files came to answer 500 for every teacher and every video: the cue editor's
 * route gained a `\d+` on fileId, and the files screen builds its URL with `__FILE_ID__`.
 *
 * One test per template URL in the application, asserting only that it can be generated. It costs
 * nothing and it is the only thing standing between a routing requirement and a dead screen.
 */
class PlaceholderUrlTest extends KernelTestCase
{
    /**
     * @return iterable<string, array{string, array<string, string|int>}>
     */
    public static function templateUrls(): iterable
    {
        yield 'video files - cue editor' => ['app_video_resource_cues', ['resourceId' => 1, 'fileId' => '__FILE_ID__']];
        yield 'video files - delete' => ['app_video_resource_file_delete', ['resourceId' => 1, 'fileId' => '__FILE_ID__']];
        yield 'audio files - delete' => ['app_audio_recording_file_delete', ['recordingId' => 1, 'fileId' => '__FILE_ID__']];
        yield 'cue editor - delete' => ['app_video_resource_cue_delete', ['resourceId' => 1, 'fileId' => 1, 'cueId' => '__CUE_ID__']];
        yield 'student video - question' => ['app_student_work_video_cue', ['assignmentId' => 1, 'cueId' => '__CUE_ID__']];
        yield 'account operations - profile' => ['app_directory_users_edit', ['id' => '__ID__']];
        yield 'account operations - retry' => ['app_directory_account_retry', ['id' => '__ID__']];
    }

    /**
     * @param array<string, string|int> $parameters
     */
    #[\PHPUnit\Framework\Attributes\DataProvider('templateUrls')]
    public function testTheTemplateUrlCanBeGenerated(string $route, array $parameters): void
    {
        self::bootKernel();
        /** @var UrlGeneratorInterface $generator */
        $generator = self::getContainer()->get('router');

        // The assertion is that this does not throw an InvalidParameterException.
        self::assertNotSame('', $generator->generate($route, $parameters));
    }
}
