<?php

declare(strict_types=1);

namespace App\Controller;

use App\Attribute\RequiresFeature;
use App\Entity\SchoolMailSignature;
use App\Entity\User;
use App\Enum\Feature;
use App\Repository\SchoolMailSignatureRepository;
use App\Service\StudentMailboxResolver;
use App\Service\StudentSignatureBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

/**
 * "My signature" - the signature added to every school mail (design_handoff_stage_alternance,
 * screen 3f).
 *
 * Generated by default from what the platform knows, every field editable by the student, and a
 * "Restore the default signature" button. That button deletes the row rather than rewriting it with
 * the computed values: the point of the default is that it keeps following its sources.
 */
#[IsGranted('ROLE_STUDENT')]
#[RequiresFeature(Feature::SchoolMail)]
class SchoolMailSignatureController extends AbstractController
{
    public function __construct(
        private readonly SchoolMailSignatureRepository $signatureRepository,
        private readonly StudentSignatureBuilder $signatureBuilder,
        private readonly StudentMailboxResolver $mailboxResolver,
        private readonly EntityManagerInterface $entityManager,
    ) {
    }

    #[Route(path: '/school-mail/signature', name: 'app_school_mail_signature', methods: ['GET'])]
    public function show(): Response
    {
        /** @var User $student */
        $student = $this->getUser();

        return $this->renderSignature($student);
    }

    #[Route(path: '/school-mail/signature/save', name: 'app_school_mail_signature_save', methods: ['POST'])]
    public function save(Request $request): Response
    {
        /** @var User $student */
        $student = $this->getUser();

        if (!$this->isCsrfTokenValid('school_mail_signature', (string) $request->request->get('_token'))) {
            throw $this->createAccessDeniedException();
        }

        $signature = $this->signatureRepository->findOneForStudent($student)
            ?? (new SchoolMailSignature())->setStudent($student);

        $signature
            ->setFullName(trim((string) $request->request->get('fullName', '')))
            ->setProgramLabel(trim((string) $request->request->get('programLabel', '')))
            ->setEmailAddress(trim((string) $request->request->get('emailAddress', '')))
            ->setPhone(trim((string) $request->request->get('phone', '')))
            ->setLinkedinUrl(trim((string) $request->request->get('linkedinUrl', '')))
            ->setGithubUrl(trim((string) $request->request->get('githubUrl', '')))
            ->touch();

        if (null === $signature->getId()) {
            $this->entityManager->persist($signature);
        }

        $this->entityManager->flush();
        $this->addFlash('success', 'schoolMailSignatureSavedFlash');

        return $this->redirectToRoute('app_school_mail_signature');
    }

    #[Route(path: '/school-mail/signature/reset', name: 'app_school_mail_signature_reset', methods: ['POST'])]
    public function reset(Request $request): Response
    {
        /** @var User $student */
        $student = $this->getUser();

        if (!$this->isCsrfTokenValid('school_mail_signature_reset', (string) $request->request->get('_token'))) {
            throw $this->createAccessDeniedException();
        }

        $signature = $this->signatureRepository->findOneForStudent($student);

        if (null !== $signature) {
            // Deleting rather than overwriting with the computed values: an untouched signature has
            // to keep following the sources it is built from.
            $this->entityManager->remove($signature);
            $this->entityManager->flush();
        }

        $this->addFlash('success', 'schoolMailSignatureResetFlash');

        return $this->redirectToRoute('app_school_mail_signature');
    }

    private function renderSignature(User $student): Response
    {
        $mailbox = $this->mailboxResolver->addressFor($student);

        return $this->render('school_mail/signature.html.twig', [
            'signature' => $this->signatureBuilder->build($student, $mailbox),
            'defaults' => $this->signatureBuilder->defaults($student, $mailbox),
            'custom' => $this->signatureRepository->findOneForStudent($student),
            'mailbox' => $mailbox,
        ]);
    }
}
