<?php

declare(strict_types=1);

namespace App\Controller\Portfolio;

use Symfony\Component\HttpFoundation\HeaderUtils;
use Symfony\Component\HttpFoundation\Response;

/**
 * Hands generated bytes to the browser as a download - PDF or .xlsx - with a name a person can read.
 */
trait PortfolioDownloadTrait
{
    private function download(string $bytes, string $filename, string $mime): Response
    {
        $ascii = (string) preg_replace('/[^A-Za-z0-9._-]+/', '-', (string) iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $filename));

        return new Response($bytes, Response::HTTP_OK, [
            'Content-Type' => $mime,
            'Content-Disposition' => HeaderUtils::makeDisposition(HeaderUtils::DISPOSITION_ATTACHMENT, $filename, '' === trim($ascii, '-') ? 'portfolio' : $ascii),
            'Cache-Control' => 'private, no-store',
        ]);
    }

    private static function slug(string $value): string
    {
        $slug = strtolower(trim((string) preg_replace('/[^A-Za-z0-9]+/', '-', (string) iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $value)), '-'));

        return '' === $slug ? 'portfolio' : $slug;
    }
}
